using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AngularPoc.Permissions;
using AngularPoc.Feedbacks;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AngularPoc.Shared;

namespace AngularPoc.Feedbacks
{
    public class FeedbacksAppService : FeedbacksAppServiceBase, IFeedbacksAppService
    {
        //<suite-custom-code-autogenerated>
        public FeedbacksAppService(IFeedbackRepository feedbackRepository, FeedbackManager feedbackManager, IDistributedCache<FeedbackDownloadTokenCacheItem, string> downloadTokenCache)
            : base(feedbackRepository, feedbackManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}